"""make branch manager branch optional and update both brnach manager and branch to set backpropgates

Revision ID: 3c9d7e040349
Revises: d3536fe521d0
Create Date: 2026-08-13 12:12:44.124269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9d7e040349'
down_revision: Union[str, Sequence[str], None] = 'd3536fe521d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch_managers', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch_managers', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
