"""branch inventory added

Revision ID: 3e466e6c653a
Revises: a651214d158c
Create Date: 2026-08-17 11:45:54.043229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e466e6c653a'
down_revision: Union[str, Sequence[str], None] = 'a651214d158c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_variant_id', name='uq_branch_product_variant')
    )
    op.create_index(op.f('ix_branch_inventory_branch_id'), 'branch_inventory', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_inventory_id'), 'branch_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_branch_inventory_product_variant_id'), 'branch_inventory', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_branch_inventory_unique_id'), 'branch_inventory', ['unique_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_inventory_unique_id'), table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_product_variant_id'), table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_id'), table_name='branch_inventory')
    op.drop_index(op.f('ix_branch_inventory_branch_id'), table_name='branch_inventory')
    op.drop_table('branch_inventory')
    # ### end Alembic commands ###
