"""branch inventory updated

Revision ID: 76de78540262
Revises: 3e466e6c653a
Create Date: 2026-08-17 12:15:04.893463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76de78540262'
down_revision: Union[str, Sequence[str], None] = '3e466e6c653a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_inventory_unique_id'), table_name='branch_inventory')
    op.drop_column('branch_inventory', 'unique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_inventory', sa.Column('unique_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_branch_inventory_unique_id'), 'branch_inventory', ['unique_id'], unique=True)
    # ### end Alembic commands ###
